-- MySQL Script generated by MySQL Workbench
-- Wed Nov 23 17:19:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficina_refinado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oficina_refinado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficina_refinado` DEFAULT CHARACTER SET utf8 ;
USE `oficina_refinado` ;

-- -----------------------------------------------------
-- Table `oficina_refinado`.`pessoas`
-- -----------------------------------------------------

-- Conditionally drop objects.
SELECT 'pessoas' AS 'Drop Table';
DROP TABLE IF EXISTS `pessoas`;

CREATE TABLE IF NOT EXISTS `pessoas` (
  `idPessoas` INT NOT NULL AUTO_INCREMENT,
  `Nome_psa` VARCHAR(60) NOT NULL,
  `Tipo_psa` VARCHAR(2) NOT NULL,
  `Cliente_psa` CHAR(1) NOT NULL,
  `Fornecedor_psa` CHAR(1) NOT NULL,
  `Email_psa` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPessoas`),
  UNIQUE INDEX `idClientes_UNIQUE` (`idPessoas` ASC)
  )ENGINE = InnoDB;

ALTER TABLE `Pessoas` AUTO_INCREMENT = 1001;
-- -----------------------------------------------------
-- Table `oficina_refinado`.`Estados`
-- -----------------------------------------------------
SELECT 'estados' AS 'Drop Table';
DROP TABLE IF EXISTS `estados`;

CREATE TABLE IF NOT EXISTS `Estados` (
  `idEstados` INT NOT NULL AUTO_INCREMENT,
  `Nome_est` VARCHAR(45) NOT NULL,
  `UF_est` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`idEstados`),
  UNIQUE INDEX `idEstados_UNIQUE` (`idEstados` ASC),
  UNIQUE INDEX `Nome_est_UNIQUE` (`Nome_est` ASC)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Pessoa_Endereco`
-- -----------------------------------------------------
SELECT 'pessoa_endereco' AS 'Drop Table';
DROP TABLE IF EXISTS `pessoa_endereco`;

CREATE TABLE IF NOT EXISTS `Pessoa_Endereco` (
  `idPessoa_Endereco` INT NOT NULL AUTO_INCREMENT,
  `Logradouro_end` VARCHAR(100) NOT NULL,
  `Estados_idEstados` INT NOT NULL,
  `Pessoas_idPessoas` INT NOT NULL,
  `Numero_end` VARCHAR(10) NULL DEFAULT NULL,
  `Bairro_end` VARCHAR(45) NOT NULL,
  `Pessoa_Enderecocol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPessoa_Endereco`),
  UNIQUE INDEX `idPessoa_Endereco_UNIQUE` (`idPessoa_Endereco` ASC),
  INDEX `fk_Pessoa_Endereco_Estados1_idx` (`Estados_idEstados` ASC),
  INDEX `fk_Pessoa_Endereco_Pessoas1_idx` (`Pessoas_idPessoas` ASC),
  CONSTRAINT `fk_Pessoa_Endereco_Estados1`
    FOREIGN KEY (`Estados_idEstados`)
    REFERENCES `oficina_refinado`.`Estados` (`idEstados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Endereco_Pessoas1`
    FOREIGN KEY (`Pessoas_idPessoas`)
    REFERENCES `oficina_refinado`.`Pessoas` (`idPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Cidades`
-- -----------------------------------------------------
SELECT 'cidades' AS 'Drop Table';
DROP TABLE IF EXISTS `cidades`;

CREATE TABLE IF NOT EXISTS `Cidades` (
  `idCidades` INT NOT NULL AUTO_INCREMENT,
  `Estados_idEstados` INT NOT NULL,
  `Nome_cid` VARCHAR(120) NOT NULL,
  `Pessoa_Endereco_idPessoa_Endereco` INT NOT NULL,
  PRIMARY KEY (`idCidades`, `Estados_idEstados`),
  UNIQUE INDEX `idCidades_UNIQUE` (`idCidades` ASC),
  INDEX `fk_Cidades_Estados_idx` (`Estados_idEstados` ASC),
  INDEX `fk_Cidades_Pessoa_Endereco1_idx` (`Pessoa_Endereco_idPessoa_Endereco` ASC),
  CONSTRAINT `fk_Cidades_Estados`
    FOREIGN KEY (`Estados_idEstados`)
    REFERENCES `oficina_refinado`.`Estados` (`idEstados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cidades_Pessoa_Endereco1`
    FOREIGN KEY (`Pessoa_Endereco_idPessoa_Endereco`)
    REFERENCES `oficina_refinado`.`Pessoa_Endereco` (`idPessoa_Endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Clientes`
-- -----------------------------------------------------
SELECT 'clientes' AS 'Drop Table';
DROP TABLE IF EXISTS `clientes`;

CREATE TABLE IF NOT EXISTS `Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Pessoas_idPessoas` INT NOT NULL,
  `DESDE_cli` DATE NOT NULL,
  `DataCadastro_cli` DATE NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `fk_Clientes_Pessoas1_idx` (`Pessoas_idPessoas` ASC),
  CONSTRAINT `fk_Clientes_Pessoas1`
    FOREIGN KEY (`Pessoas_idPessoas`)
    REFERENCES `oficina_refinado`.`Pessoas` (`idPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;

select * from clientes;
-- -----------------------------------------------------
-- Table `oficina_refinado`.`Pessoa_Fisica`
-- -----------------------------------------------------
-- Conditionally drop objects.
SELECT 'pessoa_fisica' AS 'Drop Table';
DROP TABLE IF EXISTS `pessoa_fisica`;

CREATE TABLE IF NOT EXISTS `pessoa_fisica` (
  `idPessoa_Fisica` INT NOT NULL AUTO_INCREMENT,
  `Pessoas_idPessoas` INT NOT NULL,
  `CPF_fis` VARCHAR(45) NOT NULL,
  `Datanas_fis` DATE NOT NULL,
  `Genero_fis` CHAR(1) NOT NULL,
  `Nacionalidade_fis` VARCHAR(100) NOT NULL,
  `Naturalidade_fis` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPessoa_Fisica`),
  UNIQUE INDEX `idPessoa_Fisica_UNIQUE` (`idPessoa_Fisica` ASC),
  UNIQUE INDEX `CPF_fis_UNIQUE` (`CPF_fis` ASC),
  INDEX `fk_Pessoa_Fisica_Pessoas1_idx` (`Pessoas_idPessoas` ASC),
  CONSTRAINT `fk_Pessoa_Fisica_Pessoas1`
    FOREIGN KEY (`Pessoas_idPessoas`)
    REFERENCES `oficina_refinado`.`Pessoas` (`idPessoas`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Pessoa_Juridica`
-- -----------------------------------------------------
-- Conditionally drop objects.
SELECT 'pessoa_juridica' AS 'Drop Table';
DROP TABLE IF EXISTS `pessoa_juridica`;

CREATE TABLE IF NOT EXISTS `pessoa_juridica` (
  `idPessoa_Juridica` INT NOT NULL AUTO_INCREMENT,
  `Pessoas_idPessoas` INT NOT NULL,
  `CNPJ_jur` VARCHAR(14) NOT NULL,
  `NomeFantasia_jur` VARCHAR(100) NOT NULL,
  `Inscricao_Estadual_jur` VARCHAR(15) NOT NULL,
  `Inscricao_Municipal_jur` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idPessoa_Juridica`),
  UNIQUE INDEX `idPessoa_Juridica_UNIQUE` (`idPessoa_Juridica` ASC),
  INDEX `fk_Pessoa_Juridica_Pessoas1_idx` (`Pessoas_idPessoas` ASC),
  CONSTRAINT `fk_Pessoa_Juridica_Pessoas1`
    FOREIGN KEY (`Pessoas_idPessoas`)
    REFERENCES `oficina_refinado`.`Pessoas` (`idPessoas`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Telefones`
-- -----------------------------------------------------
-- Conditionally drop objects.
SELECT 'telefones' AS 'Drop Table';
DROP TABLE IF EXISTS `telefones`;

CREATE TABLE IF NOT EXISTS `Telefones` (
  `idTelefones` INT NOT NULL AUTO_INCREMENT,
  `Pessoas_idPessoas` INT NOT NULL,
  `Tipo_tel` CHAR(1) NOT NULL,
  `Numero_tel` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idTelefones`),
  UNIQUE INDEX `idTelefones_UNIQUE` (`idTelefones` ASC),
  UNIQUE INDEX `Numero_tel_UNIQUE` (`Numero_tel` ASC),
  INDEX `fk_Telefones_Pessoas1_idx` (`Pessoas_idPessoas` ASC),
  CONSTRAINT `fk_Telefones_Pessoas1`
    FOREIGN KEY (`Pessoas_idPessoas`)
    REFERENCES `oficina_refinado`.`Pessoas` (`idPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Fornecedor`
-- -----------------------------------------------------
SELECT 'fornecedor' AS 'Drop Table';
DROP TABLE IF EXISTS `fornecedor`;

CREATE TABLE IF NOT EXISTS `Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `Pessoas_idPessoas` INT NOT NULL,
  `Data_cadastro` DATE NOT NULL,
  `DESDE` DATE NOT NULL,
  `Observacao` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `idFornecedor_UNIQUE` (`idFornecedor` ASC),
  UNIQUE INDEX `Data_cadastro_UNIQUE` (`Data_cadastro` ASC),
  UNIQUE INDEX `DESDE_UNIQUE` (`DESDE` ASC),
  INDEX `fk_Fornecedor_Pessoas1_idx` (`Pessoas_idPessoas` ASC),
  CONSTRAINT `fk_Fornecedor_Pessoas1`
    FOREIGN KEY (`Pessoas_idPessoas`)
    REFERENCES `oficina_refinado`.`Pessoas` (`idPessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Cargos`
-- -----------------------------------------------------
SELECT 'cargos' AS 'Drop Table';
DROP TABLE IF EXISTS `cargos`;

CREATE TABLE IF NOT EXISTS `Cargos` (
  `idCargos` INT NOT NULL AUTO_INCREMENT,
  `Nome_car` VARCHAR(45) NOT NULL,
  `Descricao_car` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idCargos`),
  UNIQUE INDEX `idCargos_UNIQUE` (`idCargos` ASC),
  UNIQUE INDEX `Nome_car_UNIQUE` (`Nome_car` ASC)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Setor`
-- -----------------------------------------------------
SELECT 'setor' AS 'Drop Table';
DROP TABLE IF EXISTS `setor`;

CREATE TABLE IF NOT EXISTS `Setor` (
  `idSetor` INT NOT NULL AUTO_INCREMENT,
  `Nome_set` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idSetor`),
  UNIQUE INDEX `idSetor_UNIQUE` (`idSetor` ASC)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Colaborador`
-- -----------------------------------------------------
SELECT 'colaborador' AS 'Drop Table';
DROP TABLE IF EXISTS `colaborador`;

CREATE TABLE IF NOT EXISTS `Colaborador` (
  `idColaborador` INT NOT NULL AUTO_INCREMENT,
  `Pessoas_idPessoas` INT NOT NULL,
  `Cargos_idCargos` INT NOT NULL,
  `Setor_idSetor` INT NOT NULL,
  `Matricula_col` VARCHAR(10) NOT NULL,
  `DataCadastro_col` DATE NOT NULL,
  `DataAdmissao_col` DATE NOT NULL,
  `DataDemissao_col` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idColaborador`),
  UNIQUE INDEX `idColaborador_UNIQUE` (`idColaborador` ASC),
  UNIQUE INDEX `Matricula_col_UNIQUE` (`Matricula_col` ASC),
  INDEX `fk_Colaborador_Pessoas1_idx` (`Pessoas_idPessoas` ASC),
  INDEX `fk_Colaborador_Cargos1_idx` (`Cargos_idCargos` ASC),
  INDEX `fk_Colaborador_Setor1_idx` (`Setor_idSetor` ASC),
  CONSTRAINT `fk_Colaborador_Pessoas1`
    FOREIGN KEY (`Pessoas_idPessoas`)
    REFERENCES `oficina_refinado`.`Pessoas` (`idPessoas`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Cargos1`
    FOREIGN KEY (`Cargos_idCargos`)
    REFERENCES `oficina_refinado`.`Cargos` (`idCargos`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Setor1`
    FOREIGN KEY (`Setor_idSetor`)
    REFERENCES `oficina_refinado`.`Setor` (`idSetor`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;

select * from colaborador;
-- -----------------------------------------------------
-- Table `oficina_refinado`.`Tipo`
-- -----------------------------------------------------
SELECT 'tipo' AS 'Drop Table';
DROP TABLE IF EXISTS `tipo`;

CREATE TABLE IF NOT EXISTS `Tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idTipo`),
  UNIQUE INDEX `idTipo_UNIQUE` (`idTipo` ASC)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Fornecedor_has_Tipo`
-- -----------------------------------------------------
SELECT 'fornecedor_has_tipo' AS 'Drop Table';
DROP TABLE IF EXISTS `fornecedor_has_tipo`;

CREATE TABLE IF NOT EXISTS `Fornecedor_has_Tipo` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Tipo_idTipo` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Tipo_idTipo`),
  INDEX `fk_Fornecedor_has_Tipo_Tipo1_idx` (`Tipo_idTipo` ASC),
  INDEX `fk_Fornecedor_has_Tipo_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC),
  CONSTRAINT `fk_Fornecedor_has_Tipo_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `oficina_refinado`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Tipo_Tipo1`
    FOREIGN KEY (`Tipo_idTipo`)
    REFERENCES `oficina_refinado`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Servico`
-- -----------------------------------------------------
SELECT 'servico' AS 'Drop Table';
DROP TABLE IF EXISTS `servico`;

CREATE TABLE IF NOT EXISTS `Servico` (
  `id_Servico` INT NOT NULL AUTO_INCREMENT,
  `Nome_ser` VARCHAR(45) NOT NULL,
  `Valor_ser` FLOAT NOT NULL,
  PRIMARY KEY (`id_Servico`),
  UNIQUE INDEX `idEstoque_UNIQUE` (`id_Servico` ASC)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`montadora`
-- -----------------------------------------------------
-- Conditionally drop objects.
SELECT 'montadora' AS 'Drop Table';
DROP TABLE IF EXISTS `montadora`;

CREATE TABLE IF NOT EXISTS `montadora` (
  `idMontadora` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMontadora`),
  UNIQUE INDEX `idMontadora_UNIQUE` (`idMontadora` ASC)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Modelo`
-- -----------------------------------------------------

-- Conditionally drop objects.
SELECT 'modelo' AS 'Drop Table';
DROP TABLE IF EXISTS `modelo`;

CREATE TABLE IF NOT EXISTS `modelo` (
  `idModelo` INT NOT NULL AUTO_INCREMENT,
  `Nome_mod` VARCHAR(45) NOT NULL,
  `Tipo_mod` VARCHAR(8) NULL DEFAULT NULL,
  `Modelo_idModelo` INT NOT NULL,
  PRIMARY KEY (`idModelo`, `Modelo_idModelo`),
  UNIQUE INDEX `idModelo_UNIQUE` (`idModelo` ASC),
  INDEX `fk_Modelo_Modelo1_idx` (`Modelo_idModelo` ASC),
  CONSTRAINT `fk_Modelo_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `oficina_refinado`.`Modelo` (`idModelo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`COR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COR` (
  `idCOR` INT NOT NULL AUTO_INCREMENT,
  `Nome_cor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCOR`),
  UNIQUE INDEX `idCOR_UNIQUE` (`idCOR` ASC)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Veículo`
-- -----------------------------------------------------
SELECT 'veiculo' AS 'Drop Table';
DROP TABLE IF EXISTS `veiculo`;

CREATE TABLE IF NOT EXISTS `veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `Modelo_idModelo` INT NOT NULL,
  `Montadora_idMontadora` INT NOT NULL,
  `COR_idCOR` INT NOT NULL,
  `Placa_vec` VARCHAR(10) NOT NULL,
  `Km_vec` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idVeiculo`, `Modelo_idModelo`, `Montadora_idMontadora`, `COR_idCOR`),
  CONSTRAINT `fk_Veiculo_ModeloCARRO`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `oficina_refinado`.`Modelo` (`idModelo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_MontadoraCARRO`
    FOREIGN KEY (`Montadora_idMontadora`)
    REFERENCES `oficina_refinado`.`Montadora` (`idMontadora`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_CORCARRO`
    FOREIGN KEY (`COR_idCOR`)
    REFERENCES `oficina_refinado`.`COR` (`idCOR`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Ordem`
-- -----------------------------------------------------
SELECT 'ordem' AS 'Drop Table';
DROP TABLE IF EXISTS `ordem`;

CREATE TABLE IF NOT EXISTS `Ordem` (
  `idOrdem` INT NOT NULL AUTO_INCREMENT,
  `Clientes_idClientes` INT NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  `Concluida_ord` TINYINT NULL DEFAULT NULL,
  `Paga_ord` TINYINT NULL DEFAULT NULL,
  `Datareg_ord` DATE NULL DEFAULT NULL,
  `Datapag_ord` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idOrdem`, `Veiculo_idVeiculo`, `Clientes_idClientes`),
  CONSTRAINT `fk_Ordem_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `oficina_refinado`.`Veiculo` (`idVeiculo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `oficina_refinado`.`Clientes` (`idClientes`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;

desc clientes;
-- -----------------------------------------------------
-- Table `oficina_refinado`.`Ordem_Servico`
-- -----------------------------------------------------
SELECT 'ordem_servico' AS 'Drop Table';
DROP TABLE IF EXISTS `ordem_servico`;

CREATE TABLE IF NOT EXISTS `Ordem_Servico` (
  `idOrdem_Servico` INT NOT NULL AUTO_INCREMENT,
  `Ordem_idOrdem` INT NOT NULL,
  `Servico_id_Servico` INT NOT NULL,
  `Descricao` VARCHAR(250) NOT NULL,
  `Valor_os` FLOAT NOT NULL,
  `Data_os` DATE NOT NULL,
  `Status_os` CHAR(1) NOT NULL,
  PRIMARY KEY (`idOrdem_Servico`, `Servico_id_Servico`),
  UNIQUE INDEX `idOrdem_Servico_UNIQUE` (`idOrdem_Servico` ASC),
  INDEX `fk_Ordem_Servico_Ordem1_idx` (`Ordem_idOrdem` ASC),
  INDEX `fk_Ordem_Servico_Servico1_idx` (`Servico_id_Servico` ASC),
  CONSTRAINT `fk_Ordem_Servico_Ordem1`
    FOREIGN KEY (`Ordem_idOrdem`)
    REFERENCES `oficina_refinado`.`Ordem` (`idOrdem`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Servico_Servico1`
    FOREIGN KEY (`Servico_id_Servico`)
    REFERENCES `oficina_refinado`.`Servico` (`id_Servico`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Nota_Fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_refinado`.`Nota_Fiscal` (
  `idNota_Fiscal` INT NOT NULL AUTO_INCREMENT,
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Nota_Fiscalcol` VARCHAR(45) NOT NULL,
  `Data_Compra_nf` DATE NOT NULL,
  `Data_Entrada_nf` DATE NOT NULL,
  PRIMARY KEY (`idNota_Fiscal`),
  UNIQUE INDEX `idNota_Fiscal_UNIQUE` (`idNota_Fiscal` ASC),
  UNIQUE INDEX `Nota_Fiscalcol_UNIQUE` (`Nota_Fiscalcol` ASC),
  INDEX `fk_Nota_Fiscal_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC),
  CONSTRAINT `fk_Nota_Fiscal_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `oficina_refinado`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Estoque`
-- -----------------------------------------------------
SELECT 'estoque' AS 'Drop Table';
DROP TABLE IF EXISTS `estoque`;

CREATE TABLE IF NOT EXISTS `Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `Nota_Fiscal_idNota_Fiscal` INT NOT NULL,
  `Nome_est` VARCHAR(45) NOT NULL,
  `Valor_est` FLOAT NOT NULL,
  `Quant_est` INT NOT NULL,
  `Codigo_est` INT NOT NULL,
  PRIMARY KEY (`idEstoque`),
  CONSTRAINT `fk_Estoque_Nota_Fiscal1`
    FOREIGN KEY (`Nota_Fiscal_idNota_Fiscal`)
    REFERENCES `oficina_refinado`.`Nota_Fiscal` (`idNota_Fiscal`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Fornecedor_has_Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_refinado`.`Fornecedor_has_Estoque` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Estoque_idEstoque`),
  INDEX `fk_Fornecedor_has_Estoque_Estoque1_idx` (`Estoque_idEstoque` ASC),
  INDEX `fk_Fornecedor_has_Estoque_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC),
  CONSTRAINT `fk_Fornecedor_has_Estoque_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `oficina_refinado`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `oficina_refinado`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Estoque_has_Ordem_Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina_refinado`.`Estoque_has_Ordem_Servico` (
  `Estoque_idEstoque` INT NOT NULL,
  `Ordem_Servico_idOrdem_Servico` INT NOT NULL,
  PRIMARY KEY (`Estoque_idEstoque`, `Ordem_Servico_idOrdem_Servico`),
  INDEX `fk_Estoque_has_Ordem_Servico_Ordem_Servico1_idx` (`Ordem_Servico_idOrdem_Servico` ASC),
  INDEX `fk_Estoque_has_Ordem_Servico_Estoque1_idx` (`Estoque_idEstoque` ASC),
  CONSTRAINT `fk_Estoque_has_Ordem_Servico_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `oficina_refinado`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_has_Ordem_Servico_Ordem_Servico1`
    FOREIGN KEY (`Ordem_Servico_idOrdem_Servico`)
    REFERENCES `oficina_refinado`.`Ordem_Servico` (`idOrdem_Servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Equipe`
-- -----------------------------------------------------
SELECT 'equipe' AS 'Drop Table';
DROP TABLE IF EXISTS `equipe`;

CREATE TABLE IF NOT EXISTS `equipe` (
  `idEquipe` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEquipe`),
  UNIQUE INDEX `idEquipe_UNIQUE` (`idEquipe` ASC)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Colaborador_has_Equipe`
-- -----------------------------------------------------
SELECT 'colaborador_has_Equipe' AS 'Drop Table';
DROP TABLE IF EXISTS `colaborador_has_Equipe`;

CREATE TABLE IF NOT EXISTS `Colaborador_has_Equipe` (
  `Colaborador_idColaborador` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`Colaborador_idColaborador`, `Equipe_idEquipe`),
  INDEX `fk_Colaborador_has_Equipe_Equipe1_idx` (`Equipe_idEquipe` ASC),
  INDEX `fk_Colaborador_has_Equipe_Colaborador1_idx` (`Colaborador_idColaborador` ASC),
  CONSTRAINT `fk_Colaborador_has_Equipe_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `oficina_refinado`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_has_Equipe_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `oficina_refinado`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina_refinado`.`Ordem_has_Colaborador_has_Equipe`
-- -----------------------------------------------------

SELECT 'ordem_has_colaborador_has_Equipe' AS 'Drop Table';
DROP TABLE IF EXISTS `Ordem_has_Colaborador_has_Equipe`;

CREATE TABLE IF NOT EXISTS `Ordem_has_Colaborador_has_Equipe` (
  `Ordem_idOrdem` INT NOT NULL,
  `Colaborador_has_Equipe_Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`Ordem_idOrdem`, `Colaborador_has_Equipe_Equipe_idEquipe`),
  CONSTRAINT `fk_Ordem_has_Colaborador_has_Equipe_Ordem1`
    FOREIGN KEY (`Ordem_idOrdem`)
    REFERENCES `oficina_refinado`.`Ordem` (`idOrdem`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_has_Colaborador_has_Equipe_Colaborador_has_Equipe1`
    FOREIGN KEY (`Colaborador_has_Equipe_Equipe_idEquipe`)
    REFERENCES `oficina_refinado`.`Colaborador_has_Equipe` (`Equipe_idEquipe`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
    )ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
